name: xyzplugin
main: xyzplugin\main
version: 2.3.0
api: 3.0.0
author: gamesukimanIRS
authors: 僕にこのプラグインについてたくさんの助言をして下さった皆様
commands:
  xyz:
    description: "自分の座標を調べます。"
    usage: "/xyz"
  xyzhelp:
    description: "xyzpluginのヘルプを表示します"
    usage: "/xyzhelp"

