name: xyzplugin
main: xyzplugin\Main
version: 2.3.2
api: 
  - 3.0.0
  - 4.0.0
author: gamesukimanIRS
commands:
  xyz:
    description: "自分、他人の座標を調べます。"
    usage: "/xyz <null or Name>"
  xyzhelp:
    description: "xyzpluginのヘルプを表示します"
    usage: "/xyzhelp"

