name: xyzplugin
main: xyzplugin\main
version: 2.0.0
api: 3.0.0
author: gamesukimanIRS
authors: 僕にこのプラグインについてたくさんの助言をして下さった皆様
commands:
  xyz:
    description: "自分の座標を調べます。"
    usage: "/xyz"
  xyzhelp:
    description: "xyzpluginのヘルプを表示します"
    usage: "/xyzhelp"
  xyzhelp-keikoku:
    description: "xyzpluginの警告看板のヘルプを表示します"
    usage: "/xyzhelp-keikoku"
  xyzhelp-keikoku-bukken:
    description: "xyzpluginの違法物件の警告看板のヘルプを表示します"
    usage: "/xyzhelp-keikoku-bukken"

